product/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),

]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    #path('addproduct/', views.addproduct, name='addproduct'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('myhomes/', views.myhomes, name='myhomes'),
    path('deletemyhomes/<int:id>', views.deletemyhomes, name='deletemyhomes'),
    path('update1/<int:id>', views.userhome_update, name='userhome_update'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),



]

özel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('home', include('home.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('product/', include('product.urls')),
    path('user/',include('user.urls')),


    path('hakkimizda', views.hakkimizda, name='hakkimizda'),
    path('referanslar', views.referanslar, name='referanslar'),
    path('iletisim', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('addproduct/', views.addproduct, name='addproduct'),#addproduct ı bütün heryere tanıtıyoruz
    path('sss/', views.faq, name='faq'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.forms import TextInput, Textarea, ModelForm
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    smtpserver = models.CharField(blank=True,max_length=20)
    smtpemail = models.CharField(blank=True,max_length=20)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title



class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=150)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message','rows':'5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '**'+self.user.username + '**' +self.user.first_name+ ' ' +self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country','image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.question

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
       full_path = [self.title]
       k = self.parent
       while k is not None:
           full_path.append(k.title)
           k = k.parent
       return '->'.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

class Product(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150,blank=False)
    keywords = models.CharField(max_length=255,blank=False)
    description = models.CharField(max_length=255,blank=False)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    ili = models.CharField(max_length=50,blank=False)
    metrekare = models.IntegerField(max_length=50,default=10)
    binayasi = models.IntegerField(max_length=250, default=1)
    kati = models.IntegerField(max_length=250, default=1)
    isitma = models.CharField(max_length=150,default='yok')
    banyosayisi = models.IntegerField(max_length=250, default=1)
    balkonsayisi = models.IntegerField(max_length=250, default=0)
    esyali = models.CharField(max_length=10, choices=STATUS)
    aidat = models.IntegerField(max_length=250, default=0)
    depozito = models.IntegerField(max_length=250, default=0)
    odasayisi = models.CharField(max_length=100, default='3+1')
    #amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=False, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class ContentImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title','image']


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.TextField(max_length=200, blank=True)
   # rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject','comment']#,'rate'

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email =forms.EmailField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last name :')

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')

product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, request
from django.shortcuts import render

# Create your views here.
from home.models import Setting
from product.models import CommentForm, Comment, Category
from user.models import AddProductForm

#burası açılıyorekleme yapmak için direk form settings vs tanıttık
def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    form = AddProductForm(request.POST, request.FILES)#sayfaya add product gönderiyoruz home.wievsda
    context = {'setting': setting,
               'category': category,
               'form': form,

               }
    return render(request, 'user_addproduct.html', context)

@login_required(login_url='/login') #check login
def addcomment(request,id):
     url = request.META.get('HTTP_REFERER')
     if request.method == 'POST': #POST EDİLDİYSE
         form = CommentForm(request.POST)
         if form.is_valid():
             current_user=request.user#access user session information

             data = Comment()
             data.user_id = current_user.id
             data.product_id = id
             data.subject = form.cleaned_data['subject']
             data.comment = form.cleaned_data['comment']
            #data.rate = form.cleaned_data['rate']
             data.ip = request.META.get('REMOTE_ADDR')
             data.save()#veritabanına kaydet

             messages.success(request, "yorum gönderildi saolun")


             return HttpResponseRedirect(url)

     messages.warning(request, "yorum gönderilemedi lan bişey bozuk")
     return HttpResponseRedirect(url)

home/templates/faq.html
{% extends "homebase.html" %}

{% block title %}sıkça sorulan sorular{% endblock %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />


  <script>
  $( function() {
    $( "#accordion" ).accordion();
  } );
  </script>

{% endblock %}
<!--
{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}
-->

{% block maincontent %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Anasayfa</a> </li>
                <li class="active">sıkça sorulan sorular</li>
            </ul>
        </div>
    </div>

    <div class="section">
        <div class="container">
            <div class="row">
                <table cellpadding="3" width="1200">



                    <div id="accordion">
                        {% for rs in faq %}
                        <h3 style="color:red;">&nbsp;&nbsp;&nbsp;&nbsp;{{ rs.question }}</h3>
                        <div>
                            <p> {{ rs.answer }}</p>
                       </div>
                        {% endfor %}
                    </div>


                    <!--
                    {% for rs in faq %}
                        <tr>
                            <td><strong>{{ rs.question }}</strong> </td>
                        </tr>
                        <tr>
                             <td>{{ rs.answer }} </td>
                        </tr>
                    {% endfor %}
                    -->

                </table>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/footer.html
{% load static %}
<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">

						<div class="companyinfo">
							<h2><span>e</span>-kiralık</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<!--
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe3.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png'%}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>-->

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Sekmeler</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="/user">MY ACCOUNT</a></li>
								<li><a href="/hakkimizda">Hakkımızda</a></li>
								<li><a href="/referanslar">Referanslar</a></li>
								<li><a href="/iletisim">İletişim</a></li>
								<li><a href="/sss">SSS</a></li>
							</ul>
						</div>
					</div>
				</div>
					<!--
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
                    -->

			</div>
		</div>
<!--
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
-->
	           </div>
			</div>
		</div>
</footer><!--/Footer-->

{% load static %}
 <!--   <script src="{% static 'js/jquery.js'%}"></script>-->
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
	<script src="{% static 'js/price-range.js'%}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>

home/templates/product_detail.html
{% extends "homebase.html" %}

{% block title %} {{product.title}} {% endblock %}
{% block keywords %} {{product.keywords}} {% endblock %}
{% block description %} {{product.description}} {% endblock %}

{% block head %}
   <link rel ='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}



{% block maincontent %}

<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Aramaya Buradan Başlayın</h2>
						<!--category-productsr-->
						<div class="panel-group category-products" id="accordian">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											KATEGORİLER
										</a>
									</h4>
								</div>
								<div id="sportswear" class="panel-collapse collapse">
									<div class="panel-body">

										{% load mptt_tags %}
								<ul>
									{% recursetree category %}
										<li>
											<a href="/category/{{node.id}}/{{node.slug}}">{{ node.title }} </a>

											{% if not node.is_leaf_node %}
												<ul class="children">
													<li><a href="/category/{{node.id}}/{{node.slug}}">{{ children }} </a></li>

												</ul>
											{% endif %}
										</li>
									{% endrecursetree %}
								</ul>

									</div>
								</div>
							</div>

<!--
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#womens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Womens
										</a>
									</h4>
								</div>
								<div id="womens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">Fendi</a></li>
											<li><a href="#">Guess</a></li>
											<li><a href="#">Valentino</a></li>
											<li><a href="#">Dior</a></li>
											<li><a href="#">Versace</a></li>
										</ul>
									</div>
								</div>
							</div>
							-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#"></a></h4>
								</div>
							</div>
						</div>
						<!--/category-products-->
						{% load static %}
						<div class="shipping text-center"><!--shipping-->
						<img src="{% static 'images/home/shippinggg.jpg'%}" alt="" />
					</div><!--/shipping-->

					</div>
				</div>
				<h3>{{product.title}}</h3>

				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<a href="{{product.image.url}}"><img src="{{product.image.url}}" alt=""/></a><!--büyük resim burda-->

							</div>
							<div id="similar-product" class="carousel slide" data-ride="carousel">

								  <!-- slider böyle çaışıyor  -->
								    <div class="carousel-inner">
										<div class="item active">
										  <a href="{{product.image.url}}"><img src="{{product.image.url}}" style="Height:60px" alt=""></a>

											{% for rs in images %}
										  <a href="{{rs.image.url}}"><img src="{{rs.image.url}}" style="Height:60px" alt=""></a>
											{% endfor %}

										</div>


									</div>

								  <!-- Controls -->
								  <a class="left item-control" href="#similar-product" data-slide="prev">
									<i class="fa fa-angle-left"></i>
								  </a>
								  <a class="right item-control" href="#similar-product" data-slide="next">
									<i class="fa fa-angle-right"></i>
								  </a>
							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="" class="newarrival" alt="" />
								<h2>{{product.title}}</h2>
								<!--<h5><i><b>Detaylar:&nbsp</b></i>{{product.description}}</h5>-->
								<h5><i><b>Metrekare:&nbsp</b></i>{{product.metrekare}}</h5>
								<h5><i><b>Oda Sayısı:&nbsp</b></i>{{product.odasayisi}}</h5>
								<h5><i><b>Bina Yaşı:&nbsp</b></i>{{product.binayasi}}</h5>
								<h5><i><b>Bulunduğu kat:&nbsp</b></i>{{product.kati}}</h5>
								<h5><i><b>Isıtma:&nbsp</b></i>{{product.isitma}}</h5>
								<h5><i><b>Banyo Sayısı:&nbsp</b></i>{{product.banyosayisi}}</h5>
								<h5><i><b>Balkon Sayısı:&nbsp</b></i>{{product.balkonsayisi}}</h5>
								<h5><i><b>Eşyalı:&nbsp</b></i>{{product.esyali}}</h5>
								<h5><i><b>Aidat:&nbsp</b></i>{{product.aidat}}TL</h5>
								<h5><i><b>Depozito:&nbsp</b></i>{{product.depozito}}TL</h5>



								<img src="images/product-details/rating.png" alt="" />
								<span>
									<span>{{product.price}}&nbspTL</span>
								</span>
								<p></p>

								<a href=""><img src="images/product-details/share.png" class="share img-responsive"  alt="" /></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->

					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<li><a href="#details" data-toggle="tab">Detaylar</a></li>
							</ul>
						</div>
						{{product.detail | safe}}
					</div><!--/category-tab-->

					<!-- yorum kısmı -->
					<div class="tab-pane fade active in" id="reviews" >
								<div class="col-sm-12">
									{% if messages %}
									     {% for message in messages %}
									         <div class="alert alert-{{message.tags}}" role="alert">
												 {{ message }}
											 </div>
									     {% endfor %}
									{% endif %}
									
									<p><b>YORUMLAR/YORUMLARINIZ BİZİM İÇİN DEĞERLİ TEŞEKKÜRLER</b></p>

									<form action="/product/addcomment/{{ product.id }}" method="post">
										{% csrf_token %}
										<span>
											<input required class="input" type="text" name="subject" id="id_subject" placeholder="Başlık"/>
										</span>
										<textarea required class="input" id="id_comment" name="comment" placeholder="YORUMUNUZ" ></textarea>

										{% if user.id is not None %}
										<button class="primary-btn">
											Yorum gönder
										</button>
										{% else %}
										yorum eklemek için üye olunuz
										{% endif %}
									</form>
									<br>
									<br>
								</div>
							</div>
					<!-- yorum kısmı -->
					<!--yorum gösterme kısmı-->

					<h3>Yapılan Yorumlar</h3>
					{% for rs in comments %}
                                <div>

                                    <ul>
                                        <li><a href=""><i class="fa fa-user"></i>kullanıcı-{{rs.user.first_name}}</a></li>
                                        <li><a href=""><i class="fa fa-calendar-o"></i>{{ rs.create_at }}</a></li>
                                         <!--
                                        <i class="fa fa-star{% if rs.rate < 1 %}-o empty{% endif %}"></i>
                                        <i class="fa fa-star{% if rs.rate < 2 %}-o empty{% endif %}"></i>
                                        <i class="fa fa-star{% if rs.rate < 3 %}-o empty{% endif %}"></i>
                                        <i class="fa fa-star{% if rs.rate < 4 %}-o empty{% endif %}"></i>
                                        <i class="fa fa-star{% if rs.rate < 5 %}-o empty{% endif %}"></i>
                                         -->
                                    </ul>
                                    <div>
                                        <h4>{{ rs.subject }}</h4>
                                        <p>{{ rs.comment | safe}}</p>
                                    </div>
                                    <hr>
                                </div>
                                <br>
                            {% endfor %}
                 <!--yorum gösterme kısmı-->


				</div>
			</div>
</div>




{% endblock %}