user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    #path('addproduct/', views.addproduct, name='addproduct'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('myhomes/', views.myhomes, name='myhomes'),
    path('deletemyhomes/<int:id>', views.deletemyhomes, name='deletemyhomes'),
    path('update1/<int:id>', views.userhome_update, name='userhome_update'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),



]

özel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('home', include('home.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('product/', include('product.urls')),
    path('user/',include('user.urls')),


    path('hakkimizda', views.hakkimizda, name='hakkimizda'),
    path('referanslar', views.referanslar, name='referanslar'),
    path('iletisim', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('addproduct/', views.addproduct, name='addproduct'),#addproduct ı bütün heryere tanıtıyoruz
    path('sss/', views.faq, name='faq'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.forms import TextInput, Textarea, ModelForm
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    smtpserver = models.CharField(blank=True,max_length=20)
    smtpemail = models.CharField(blank=True,max_length=20)
    smtppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title



class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=150)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message','rows':'5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return '**'+self.user.username + '**' +self.user.first_name+ ' ' +self.user.last_name

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country','image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.question

user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.forms import TextInput,EmailInput,Select,FileInput

from django import forms

from home.models import UserProfile
from product.models import Product


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username' : TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}),
            'email' : EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'last_name'}),
        }
CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir'),
    ('Antalya', 'Antalya'),
    ('kahramanmaras', 'kahramanmaras'),
    ('elazig', 'elazig'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'form-control', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'form-control', 'placeholder': 'address'}),
            'city' : Select(attrs={'class': 'input', 'placeholder': 'city'},choices=CITY),
            'country': TextInput(attrs={'class': 'form-control', 'placeholder': 'country'}),
            'image' : FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }


class UserUpdateForm1(forms.ModelForm):#ev güncellemek şistediğimöizde buraya geliyoruz
    class Meta:
        model = Product
        fields = ['category', 'title', 'keywords', 'description', 'image', 'price','ili', 'detail','slug','metrekare','binayasi','kati','banyosayisi','balkonsayisi','esyali','aidat','depozito','odasayisi','isitma']  # buraya eklenecekler
        widgets = {
            'category': Select(attrs={'class': 'form-control', 'placeholder': 'category'}, ),
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'title'}),
            'keywords': TextInput(attrs={'class': 'form-control', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'form-control', 'placeholder': 'description'}),
            'image': FileInput(attrs={'class': 'form-control', 'placeholder': 'image'}),
            'price': TextInput(attrs={'class': 'form-control', 'placeholder': 'price'}),
            'ili': TextInput(attrs={'class': 'form-control', 'placeholder': 'ili'}),
            'detail': TextInput(attrs={'class': 'form-control', 'placeholder': 'detail'}),
            'slug': TextInput(attrs={'class': 'form-control', 'placeholder': 'slug'}),
            'metrekare': TextInput(attrs={'class': 'form-control', 'placeholder': 'metrekare'}),
            'binayasi': TextInput(attrs={'class': 'form-control', 'placeholder': 'binayasi'}),
            'kati': TextInput(attrs={'class': 'form-control', 'placeholder': 'kati'}),
            'banyosayisi': TextInput(attrs={'class': 'form-control', 'placeholder': 'banyosayisi'}),
            'esyali': Select(attrs={'class': 'form-control', 'placeholder': 'esyali'}),
            'aidat': TextInput(attrs={'class': 'form-control', 'placeholder': 'aidat'}),
            'balkonsayisi': TextInput(attrs={'class': 'form-control', 'placeholder': 'balkonsayisi'}),
            'depozito': TextInput(attrs={'class': 'form-control', 'placeholder': 'depozito'}),
            'odasayisi': TextInput(attrs={'class': 'form-control', 'placeholder': 'odasayisi'}),
            'isitma': TextInput(attrs={'class': 'form-control', 'placeholder': 'isitma'}),
        }

user/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.
from home.models import UserProfile
from product.models import Category, Comment, Product, ContentImageForm, Images
from user.forms import UserUpdateForm, ProfileUpdateForm, UserUpdateForm1
from user.models import AddProductForm


def index(request):
    category = Category.objects.all()
    current_user = request.user #Access user session information
    profile = UserProfile.objects.get(user_id=current_user.id)
    #return HttpResponse(profile)
    context ={'category' : category,
              'profile' : profile,
              }
    return render(request, 'user_profile.html',context)


def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request , 'Your account has been updated!')
            return redirect('/user')

    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'user_update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user) #Important!
            messages.success(request, 'Your password was successfully update!')
            return HttpResponseRedirect('/user')
        else:
            messages.error(request, 'Please correct the error below.<br>'+ str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form' : form,
            'category' : category
        })

@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    # return HttpResponse("yorumlar")
    context = {'category': category,
               'comments': comments,
               }
    return render(request, 'user_comments.html', context)

@login_required(login_url='/login')
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'silindi')
    return HttpResponseRedirect('/user/comments')


########################################################################################################
@login_required(login_url='/login')
def myhomes(request):
    category = Category.objects.all()
    current_user = request.user
    products = Product.objects.filter(user_id=current_user.id)
    # return HttpResponse("yorumlar")
    context = {'category': category,
               'products': products,
               }
    return render(request, 'myhomes.html', context)
    #return HttpResponse("myhomesdeneme ")

@login_required(login_url='/login')
def deletemyhomes(request,id):
    current_user = request.user
    Product.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'silindi')
    return HttpResponseRedirect('/user/myhomes')



def userhome_update(request,id):#burda id yi alıyoruz product user id sine atıyoruz eşitlensin boş kalmsın diye
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        userhomeupdate_form = UserUpdateForm1(request.POST, request.FILES, instance=product)
        #profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if userhomeupdate_form.is_valid():
            userhomeupdate_form.save()
            messages.success(request , 'Your has been updated!')
            return redirect('/user/myhomes')
        else:
            messages.error(request, 'Please correct the error below.<br>' + str(userhomeupdate_form.errors))
            return HttpResponseRedirect('/user/myhomes')
    else:
        category = Category.objects.all()
        userhomeupdate_form = UserUpdateForm1(instance=product)
        context = {
            'category': category,
            'userhomeupdate_form': userhomeupdate_form,
            'product': product,
        }
        return render(request, 'userhome_update.html', context)


def contentaddimage(request, id):#product ımagesden alıyor oda producta bağşlı hepsi birbirine bağlı
    if request.method == 'POST':
        lasturl= request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST, request.FILES)
        #messages.warning(request, '1 if e giriyor :' + str(form.errors))
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.product_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'GALERİ RESMİNİZ YÜKLENDİ')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'GALERİ RESMİNİZ yüklrnirken hata oluştu :'+ str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        product = Product.objects.get(id=id)
        images = Images.objects.filter(product_id=id)
        form = ContentImageForm()
        context = {
            'product': product,
            'images': images,
            'form': form,
        }
        #messages.warning(request, '1. else düşüyor :' + str(form.errors))
        return render(request,'content_gallery.html',context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %}{{profile.user_name}} Profile{% endblock %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}



{% block maincontent %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="col-sm-3">

                    <div class="contact-form">

                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div>
                </div>
                <div class="col-sm-9">
                    <div class="contact-info">
                        <h2 class="title text-center">Change Password</h2>
                    </div>
                    {% if messages %}
                        {% for message in messages %}
                            <div style="color: #d43f3a; font-size: medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="content-section">

                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>

                                    {{ field.label_tag }}<br>

                                    {{ field }}

                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="">{{ error }}</p>
                                    {% endfor %}

                                </p>
                            {% endfor %}
                            <button class="btn btn-primary" type="submit">Save changes</button>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/content_gallery.html
<html>
<head>
	<meta charset="UTF-8">
	<title>content galeri</title>

</head>
<body>
<h2>{{ product.title }}***
	{{ product.id }}
</h2>
<hr>
{% if messages %}
{% for message in messages %}
<div style="color: #d43f3a; font-size: medium">
	{{ message|safe }}
</div>
{% endfor %}
{% endif %}

<form action="/user/contentaddimage/{{ product.id }}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="hidden" name="product_id" id="id_product_id" value="{{ product.id }}"></p>
	<label for="id_title">TİTLE:</label>
	<input type="text" name="title" class="input" placeholder="title" maxlength="50"  id="id_title"></p>
	<label for="id_image">image:</label>
	<input type="file" name="image" class="input" placeholder="image" accept="image/*"  id="id_image"> </p>
	<button class="primary-btn" type="submit">resmi yükle</button>
</form>
<h4>yüklenen resimler</h4>

{% for rs in images %}
<img src="{{ rs.image.url }}" height="175">
{% endfor %}


</body>
</html>

user/templates/myhomes.html
{% extends "homebase.html" %}

{% block title %}{{profile.user_name}} Profile{% endblock %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block maincontent %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="col-sm-3">

                    <div class="contact-form">

                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div>
                </div>
                <div class="col-sm-9">
                    <div class="contact-info">
                        <h2 class="title text-center">YÜKLEMELERİM</h2>
                        {% if messages %}
                        {% for message in messages %}
                            <div style="color: #d43f3a; font-size: medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}

                        <table class="table table-condensed">

                            <tr class="cart_menu">

                            {% for rs in products %}

                            <tr>
                                <td><h5>home</h5><a href="/product/{{ rs.id }}/{{ rs.slug }}">{{ rs.title}}</a></td>
                                <td class="text-left" ><h5>image</h5><img src="{{rs.image.url}}" style="height: 70px" alt=""></td>
                                <td><h5>Kullanıcı</h5><a href="/user">{{ rs.user}}</a></td>
                                <td><h5>category</h5>{{ rs.category }}</td>
                                <td><h5>title</h5>{{ rs.title }}</td>
                                <td><h5>keywords</h5>{{ rs.keywords }}</td>
                                <td><h5>description</h5>{{ rs.description }}</td>
                                <td><h5>price</h5>{{ rs.price }}</td>
                                <td><h5>Durum</h5>{{ rs.status }}</td>
                                <td><a href="/user/deletemyhomes/{{ rs.id }}" onclick="return confirm('silinecek onaylıyormusun')">sil</a></td>
                                <td><a href="/user/update1/{{ rs.id }}" >güncelle</a></td>
                                <td><a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}','gallery','height=600,width=800,top=50,left=150')" >galeri</a></td>

                            </tr>

                            {% endfor %}


                            </tr>

                        </table>

                    </div>
                </div>



            </div>
        </div>
    </div>
{% endblock %}

user/templates/user_addproduct.html
{% extends "homebase.html" %}

{% block title %}{{profile.user_name}} Profile{% endblock %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}

{% block head %}
<link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block maincontent %}
<div id="contact-page" class="container">
    <div class="bg">
        <div class="row">
            <div class="col-sm-3">

                <div class="contact-form">

                    <div class="status alert alert-success" style="display: none"></div>

                    {% include "user_panel.html" %}

                </div>
            </div>
            <div class="col-sm-9">
                <div class="contact-info">
                    <h2 class="title text-center">User add product</h2>


                    <table class="table table-condensed">

                        <tr class="cart_menu">
                           {% if messages %}
                              {% for message in messages %}
                                 <div style="color: #d43f3a; font-size: medium">
	                                 {{ message|safe }}
                                 </div>
                              {% endfor %}
                           {% endif %}

                            <form action="/addproduct/" method="post" enctype="multipart/form-data"><!--home views de-->
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ form.media }}
                                    {{ form.as_p }}
                                </fieldset>

                                <input class="primary-btn" type="submit" value="Add Product">

                                {% if user.id is not None %}
                                {% else %}
                                {% endif %}
                            </form>

                        </tr>

                    </table>

                </div>
            </div>



        </div>
    </div>
</div>
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %}kullanıcı yorumları{% endblock %}
{% block keywords %}yorum{% endblock %}
{% block description %}yorumlar{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block maincontent %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="col-sm-3">

                    <div class="contact-form">

                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div>
                </div>
                <div class="col-sm-9">
                    <div class="contact-info">
                        <h2 class="title text-center">User comments</h2>


                        <table class="table table-condensed">

                            <tr class="cart_menu">
                                {% if messages %}
                        {% for message in messages %}
                            <div style="color: #d43f3a; font-size: medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}

                            {% for rs in comments %}

                            <tr>

                                <td><h5>product</h5><a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">{{ rs.product.title}}</a></td>
                                <td><h5>subject</h5>{{ rs.subject }}</td>
                                <td><h5>comment</h5>{{ rs.comment }}</td>
                                <td><h5>status</h5>{{ rs.status }}</td>
                                <td><h5>oluş.tar.</h5>{{ rs.create_at }}</td>
                                <td><a href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('silinecek onaylıyormusun')">sil</a></td>
                            </tr>

                            {% endfor %}


                            </tr>

                        </table>

                    </div>
                </div>



            </div>
        </div>
    </div>
{% endblock %}

user/templates/user_panel.html
<div class="contact-info">

    <h2 class="title text-center">Kullanıcı Paneli</h2>

    <div class="panel-body">
        <ul class="text-left">
            <li><a href="/user">Kullanıcı Profili </a></li>
            <li><a href="/user/myhomes">Yüklediklerim </a></li>
            <li><a href="/user/comments">Yorumlarım </a></li>
            <li><a href="/product/">Kiralık Ev Ekle</a></li> <!--#bu direk producta gidiyo onun indexine-->
            <li><a href="/logout">Çıkış </a></li>
        </ul>
    </div>
</div>

user/templates/user_profile.html
{% extends "homebase.html" %}

{% block title %}{{profile.user_name}} Profili{% endblock %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block maincontent %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="col-sm-3">

                    <div class="contact-form">

                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div>
                </div>
                <div class="col-sm-9">
                    <div class="contact-info">
                        <h2 class="title text-center">User Infarmation</h2>



                        <table class="table table-condensed">

                            <tr class="cart_menu">

                            <tr>
                                <th class="text-left">
                                    <a href="/user/update" class="btn btn-primary">Update Profile</a>
                                    <a href="/user/password" class="btn btn-primary">Change Password</a>
                                </th>
                                <td class="text-left" ><img src="{{profile.image.url}}" style="height: 250px" alt=""></td>
                            </tr>

                            <tr>
                                <th class="text-left">Name Surname</th>
                                <td class="text-left">{{profile.user_name}}</td>
                            </tr>

                            <tr>
                                <th class="text-left">Email</th>
                                <td class="text-left">{{profile.user.email}}</td>
                            </tr>

                            <tr>
                                <th class="text-left">Phone</th>
                                <td class="text-left">{{profile.phone}}</td>
                            </tr>

                            <tr>
                                <th class="text-left">Address</th>
                                <td class="text-left">{{profile.address}}</td>
                            </tr>

                            <tr>
                                <th class="text-left">City</th>
                                <td class="text-left">{{profile.city}}</td>
                            </tr>

                            <tr>
                                <th class="text-left">Country</th>
                                <td class="text-left">{{profile.country}}</td>
                            </tr>
                            </tr>

                        </table>

                    </div>
                </div>



            </div>
        </div>
    </div>
{% endblock %}